# Simple example

In [15]:
docs = ['go india',
        'india india',
        'hip hip hurray',
        'jeetega bhai jeetega india jeetega',
        'bharat mata ki jai',
        'kohli kohli',
        'sachin sachin',
        'dhoni dhoni',
        'modi ji ki jai',
        'inquilab zindabad']

In [52]:
pip install --upgrade tensorflow


Note: you may need to restart the kernel to use updated packages.


In [17]:
pip install keras

Note: you may need to restart the kernel to use updated packages.


In [53]:
import tensorflow as tf
print(tf.__version__)


2.16.1


In [18]:
import keras

In [20]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [22]:
tokenizer = Tokenizer()

In [23]:
tokenizer.fit_on_texts(docs)

In [26]:
tokenizer.word_index

{'india': 1,
 'jeetega': 2,
 'hip': 3,
 'ki': 4,
 'jai': 5,
 'kohli': 6,
 'sachin': 7,
 'dhoni': 8,
 'go': 9,
 'hurray': 10,
 'bhai': 11,
 'bharat': 12,
 'mata': 13,
 'modi': 14,
 'ji': 15,
 'inquilab': 16,
 'zindabad': 17}

In [27]:
len(tokenizer.word_index)

17

In [28]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[9, 1],
 [1, 1],
 [3, 3, 10],
 [2, 11, 2, 1, 2],
 [12, 13, 4, 5],
 [6, 6],
 [7, 7],
 [8, 8],
 [14, 15, 4, 5],
 [16, 17]]

In [29]:
from keras.utils import pad_sequences
sequences = pad_sequences(sequences,padding='post')
sequences

array([[ 9,  1,  0,  0,  0],
       [ 1,  1,  0,  0,  0],
       [ 3,  3, 10,  0,  0],
       [ 2, 11,  2,  1,  2],
       [12, 13,  4,  5,  0],
       [ 6,  6,  0,  0,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [14, 15,  4,  5,  0],
       [16, 17,  0,  0,  0]], dtype=int32)

In [49]:
from keras import Sequential
from keras.layers import Embedding

model = Sequential()
model.add(Embedding(18,output_dim=2,input_length=5))
# Build the model with an expected input shape
model.build(input_shape=(None, 5))

model.summary()

Model: "sequential_11"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_9 (Embedding)         │ (None, 5, 2)           │            36 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 36 (144.00 B)

 Trainable params: 36 (144.00 B)

 Non-trainable params: 0 (0.00 B)

In [50]:
model.compile('adam','accuracy')

In [51]:
pred = model.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
[[[ 0.0030714   0.02540537]
  [ 0.01969293 -0.04333174]
  [-0.04638518 -0.02435811]
  [-0.04638518 -0.02435811]
  [-0.04638518 -0.02435811]]

 [[ 0.01969293 -0.04333174]
  [ 0.01969293 -0.04333174]
  [-0.04638518 -0.02435811]
  [-0.04638518 -0.02435811]
  [-0.04638518 -0.02435811]]

 [[-0.00835381 -0.02894793]
  [-0.00835381 -0.02894793]
  [-0.04005363 -0.00749971]
  [-0.04638518 -0.02435811]
  [-0.04638518 -0.02435811]]

 [[-0.00096381 -0.0364308 ]
  [-0.01187242  0.00582814]
  [-0.00096381 -0.0364308 ]
  [ 0.01969293 -0.04333174]
  [-0.00096381 -0.0364308 ]]

 [[ 0.0440704   0.00508922]
  [ 0.01564443 -0.01966836]
  [-0.01755656 -0.00383977]
  [ 0.04425592 -0.04235114]
  [-0.04638518 -0.02435811]]

 [[ 0.00670462  0.03296658]
  [ 0.00670462  0.03296658]
  [-0.04638518 -0.02435811]
  [-0.04638518 -0.02435811]
  [-0.04638518 -0.02435811]]

 [[-0.00744548  0.00015792]
  [-0.00744548  0.00015792]
  [-0.04638518 -0.02435811]
  [-0.04638518 -0.02435811

In [42]:
docs = ['go india',
        'india india',
        'hip hip hurray',
        'jeetega bhai jeetega india jeetega',
        'bharat mata ki jai',
        'kohli kohli',
        'sachin sachin',
        'dhoni dhoni',
        'modi ji ki jai',
        'inquilab zindabad']

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Embedding

# Create and fit the tokenizer
tokenizer = Tokenizer()
tokenizer.fit_on_texts(docs)

# Print the word index
print("Word Index:", tokenizer.word_index)

# Convert texts to sequences
sequences = tokenizer.texts_to_sequences(docs)

# Pad sequences to ensure uniform length
max_length = 5  # Choose an appropriate max length for padding
sequences = pad_sequences(sequences, maxlen=max_length, padding='post')

# Print the padded sequences
print("Padded Sequences:\n", sequences)

# Initialize the model
vocab_size = len(tokenizer.word_index) + 1  # Adding 1 because of reserved 0 index

model = Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=2, input_length=max_length))

# Build the model with an expected input shape
model.build(input_shape=(None, max_length))

# Print the summary
model.summary()

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Predict using the model
pred = model.predict(sequences)
print("Predictions:\n", pred)

Word Index: {'india': 1, 'jeetega': 2, 'hip': 3, 'ki': 4, 'jai': 5, 'kohli': 6, 'sachin': 7, 'dhoni': 8, 'go': 9, 'hurray': 10, 'bhai': 11, 'bharat': 12, 'mata': 13, 'modi': 14, 'ji': 15, 'inquilab': 16, 'zindabad': 17}
Padded Sequences:
 [[ 9  1  0  0  0]
 [ 1  1  0  0  0]
 [ 3  3 10  0  0]
 [ 2 11  2  1  2]
 [12 13  4  5  0]
 [ 6  6  0  0  0]
 [ 7  7  0  0  0]
 [ 8  8  0  0  0]
 [14 15  4  5  0]
 [16 17  0  0  0]]


Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_6 (Embedding)         │ (None, 5, 2)           │            36 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 36 (144.00 B)

 Trainable params: 36 (144.00 B)

 Non-trainable params: 0 (0.00 B)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
Predictions:
 [[[-0.00684917  0.01837325]
  [ 0.04960093  0.0079244 ]
  [-0.03122523 -0.03608569]
  [-0.03122523 -0.03608569]
  [-0.03122523 -0.03608569]]

 [[ 0.04960093  0.0079244 ]
  [ 0.04960093  0.0079244 ]
  [-0.03122523 -0.03608569]
  [-0.03122523 -0.03608569]
  [-0.03122523 -0.03608569]]

 [[-0.02321035  0.03385803]
  [-0.02321035  0.03385803]
  [ 0.01255417 -0.0262315 ]
  [-0.03122523 -0.03608569]
  [-0.03122523 -0.03608569]]

 [[-0.04931876 -0.04762695]
  [ 0.04077968  0.00963221]
  [-0.04931876 -0.04762695]
  [ 0.04960093  0.0079244 ]
  [-0.04931876 -0.04762695]]

 [[ 0.02783842 -0.02022352]
  [ 0.04413057  0.0439275 ]
  [ 0.03708503 -0.03634097]
  [ 0.03438396  0.03272117]
  [-0.03122523 -0.03608569]]

 [[ 0.00456573 -0.01155684]
  [ 0.00456573 -0.01155684]
  [-0.03122523 -0.03608569]
  [-0.03122523 -0.03608569]
  [-0.03122523 -0.03608569]]

 [[ 0.03847892 -0.02618983]
  [ 0.03847892 -0.02618983]
  [-0.03122523 -0.03608569]
  [-0.031225

# RNN EMBEDDING ON IMDB DATSET

In [90]:
from keras.datasets import imdb
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [91]:
# Load the IMDB dataset
vocab_size = 10000  # Limit the vocabulary size to 10,000 words
max_length = 50    # Limit the sequence length to 500 words

In [92]:
(X_train,y_train),(X_test,y_test) = imdb.load_data(num_words=vocab_size)

In [93]:
# Pad sequences to ensure uniform input length
X_train = pad_sequences(X_train, maxlen=max_length, padding='post')
X_test = pad_sequences(X_test, maxlen=max_length, padding='post')

In [94]:
X_train.shape

(25000, 50)

In [105]:
model = Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=3, input_length=max_length))
model.add(SimpleRNN(32, return_sequences=False))
model.add(Dense(1, activation='sigmoid'))
# Build the model with an expected input shape
model.build(input_shape=(None, 50))

In [106]:
# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [107]:
# Print the model summary
model.summary()

Model: "sequential_21"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_19 (Embedding)        │ (None, 50, 3)          │        30,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_7 (SimpleRNN)        │ (None, 32)             │         1,152 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 31,185 (121.82 KB)

 Trainable params: 31,185 (121.82 KB)

 Non-trainable params: 0 (0.00 B)

In [109]:
# Train the model
history = model.fit(X_train, y_train, epochs=10, validation_data=(X_test, y_test))

Epoch 1/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 18s 23ms/step - accuracy: 0.9197 - loss: 0.2148 - val_accuracy: 0.7895 - val_loss: 0.5438
Epoch 2/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 21s 27ms/step - accuracy: 0.9378 - loss: 0.1749 - val_accuracy: 0.7891 - val_loss: 0.5764
Epoch 3/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 18s 22ms/step - accuracy: 0.9555 - loss: 0.1363 - val_accuracy: 0.7836 - val_loss: 0.6622
Epoch 4/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 15s 19ms/step - accuracy: 0.9632 - loss: 0.1132 - val_accuracy: 0.7682 - val_loss: 0.7003
Epoch 5/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 15s 19ms/step - accuracy: 0.9687 - loss: 0.0994 - val_accuracy: 0.7754 - val_loss: 0.7856
Epoch 6/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 15s 19ms/step - accuracy: 0.9762 - loss: 0.0771 - val_accuracy: 0.7708 - val_loss: 0.9003
Epoch 7/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 15s 19ms/step - accuracy: 0.9790 - loss: 0.0672 - val_accuracy: 0.7668 - val_loss: 1.0521
Epoch 8/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 16s 20ms/step - accuracy: 0.9805 - loss: 0.0643 - 

## Integer encoding method

In [110]:
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [111]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()

In [119]:
X_train[0]

array([ 1415,    33,     6,    22,    12,   215,    28,    77,    52,
           5,    14,   407,    16,    82, 10311,     8,     4,   107,
         117,  5952,    15,   256,     4, 31050,     7,  3766,     5,
         723,    36,    71,    43,   530,   476,    26,   400,   317,
          46,     7,     4, 12118,  1029,    13,   104,    88,     4,
         381,    15,   297,    98,    32,  2071,    56,    26,   141,
           6,   194,  7486,    18,     4,   226,    22,    21,   134,
         476,    26,   480,     5,   144,    30,  5535,    18,    51,
          36,    28,   224,    92,    25,   104,     4,   226,    65,
          16,    38,  1334,    88,    12,    16,   283,     5,    16,
        4472,   113,   103,    32,    15,    16,  5345,    19,   178,
          32], dtype=int32)

In [113]:
len(X_train[2])

141

In [114]:
X_train = pad_sequences(X_train,padding='post',maxlen=100)
X_test = pad_sequences(X_test,padding='post',maxlen=100)

In [115]:
X_train[0]

array([ 1415,    33,     6,    22,    12,   215,    28,    77,    52,
           5,    14,   407,    16,    82, 10311,     8,     4,   107,
         117,  5952,    15,   256,     4, 31050,     7,  3766,     5,
         723,    36,    71,    43,   530,   476,    26,   400,   317,
          46,     7,     4, 12118,  1029,    13,   104,    88,     4,
         381,    15,   297,    98,    32,  2071,    56,    26,   141,
           6,   194,  7486,    18,     4,   226,    22,    21,   134,
         476,    26,   480,     5,   144,    30,  5535,    18,    51,
          36,    28,   224,    92,    25,   104,     4,   226,    65,
          16,    38,  1334,    88,    12,    16,   283,     5,    16,
        4472,   113,   103,    32,    15,    16,  5345,    19,   178,
          32], dtype=int32)

In [116]:
model = Sequential()

model.add(SimpleRNN(32,input_shape=(100,1),return_sequences=False))
model.add(Dense(1,activation='sigmoid'))

model.summary()

/Users/shinchan/anaconda3/lib/python3.10/site-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_22"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_8 (SimpleRNN)        │ (None, 32)             │         1,088 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,121 (4.38 KB)

 Trainable params: 1,121 (4.38 KB)

 Non-trainable params: 0 (0.00 B)

In [117]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

model.fit(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 19s 22ms/step - accuracy: 0.5035 - loss: 0.6958 - val_accuracy: 0.5134 - val_loss: 0.6927
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 23s 29ms/step - accuracy: 0.5073 - loss: 0.6929 - val_accuracy: 0.5129 - val_loss: 0.6923
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 26s 34ms/step - accuracy: 0.5110 - loss: 0.6925 - val_accuracy: 0.5132 - val_loss: 0.6929
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 27s 35ms/step - accuracy: 0.5067 - loss: 0.6928 - val_accuracy: 0.5124 - val_loss: 0.6926
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 24s 30ms/step - accuracy: 0.5136 - loss: 0.6927 - val_accuracy: 0.5109 - val_loss: 0.6930
